### ISSUE TITLE
Adding dependency via Maven breaks Lombok

### ISSUE THREAD

**Issue by AutonomicPerfectionist** [CoreyForsyth/annotation-constraints#1]
Upon adding this library to a project using Lombok, compilation fails due to lombok annotation processors not running.

Minimum test case:
A project with this library and Lombok as its only dependencies.
A class as follows:
```java
public class TestCase {
     @Getter
     private int testInt = 0;

     @Override
     public String toString() {
          return "" + getTestInt();

     }

}

```

Results in an error because `getTestInt()` does not exist, yet removing the dependency on this library allows it to compile. Tested using Intellij Idea 2021.3.3 on Ubuntu 21.10 using default compilation settings and Lombok plugin.

**Comment by CoreyForsyth** [comment]
I'm not able to reproduce this unfortunately. 
The closest I got was with this:
`	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<generatedSourcesDirectory>${project.build.directory}/generated-sources/</generatedSourcesDirectory>
					<annotationProcessors>
						com.annotationconstraints.processor.AnnotationConstraintProcessor
					</annotationProcessors>
				</configuration>
			</plugin>
		</plugins>
	</build>`
Which I'm pretty sure is telling maven to only use the annotation processor from this lib and no others. Tested on Intellij 2021.3 on windows + maven CLI as well, version 3.8.1.
I'm sure I'm doing something different though, I don't have much experience using maven

**Comment by AutonomicPerfectionist** [comment]
Yeah I discovered I forgot to add Lombok to the annotation processor paths, my mistake
